services:
  app:
    build: .
    container_name: recipe_swap_app
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    environment:
      - PORT=3000
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: recipe_swap_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: recipes_db
      MYSQL_USER: recipes_user
      MYSQL_PASSWORD: recipes_pass
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

volumes:
  db_data:
